// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKmlaPti1CfSjft4RS_RjJ1BqM2WAdtWM',
    appId: '1:833322629143:web:f8e2f9a365d832b1464452',
    messagingSenderId: '833322629143',
    projectId: 'e-commerce-cfcab',
    authDomain: 'e-commerce-cfcab.firebaseapp.com',
    storageBucket: 'e-commerce-cfcab.firebasestorage.app',
    measurementId: 'G-4XCF8F5LE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDP3ISwqC4lUhgacT9CEhWWFKQ23e3Jo',
    appId: '1:833322629143:android:e0a9e05f77b28751464452',
    messagingSenderId: '833322629143',
    projectId: 'e-commerce-cfcab',
    storageBucket: 'e-commerce-cfcab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSS1qUdfYkvg_ilFYNUIgff0aanDRSNs',
    appId: '1:833322629143:ios:841868bb307c3f54464452',
    messagingSenderId: '833322629143',
    projectId: 'e-commerce-cfcab',
    storageBucket: 'e-commerce-cfcab.firebasestorage.app',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqSS1qUdfYkvg_ilFYNUIgff0aanDRSNs',
    appId: '1:833322629143:ios:841868bb307c3f54464452',
    messagingSenderId: '833322629143',
    projectId: 'e-commerce-cfcab',
    storageBucket: 'e-commerce-cfcab.firebasestorage.app',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKmlaPti1CfSjft4RS_RjJ1BqM2WAdtWM',
    appId: '1:833322629143:web:5856afb90fa76ab3464452',
    messagingSenderId: '833322629143',
    projectId: 'e-commerce-cfcab',
    authDomain: 'e-commerce-cfcab.firebaseapp.com',
    storageBucket: 'e-commerce-cfcab.firebasestorage.app',
    measurementId: 'G-S5212E6QEM',
  );
}
