name: front_end
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.8.1
  intl: ^0.20.2
  http: ^1.3.0
  flutter_native_splash: ^2.4.4
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  readmore: ^3.0.0

  # icons
  iconsax_flutter: ^1.0.0

  # state management
  get: 4.7.2
  get_storage: ^2.1.1
  shared_preferences: ^2.5.2

  # firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #------------------- Local Assets ------------------- #
  assets:
    - assets/

  #------------------- Local Fonts ------------------- #

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets\images\logo_light.png
  image_dark: assets\images\logo_dark.png
  android: true
  ios: true
# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
